plugins { id 'com.android.application' }

android {
    namespace 'ru.homebudget.app'
    compileSdk 35
    buildToolsVersion '34.0.0'
    defaultConfig {
        applicationId 'ru.homebudget.app'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
